spring:
  jwt:
    secret: ${jwt_secret}

  config:
    activate:
      on-profile: common-local
  datasource:
    url: ${mysql_local_url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql_local_username}
    password: ${mysql_local_password}

  servlet:
    multipart:
      max-file-size: 25GB
      max-request-size: 25GB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false
  cloud:
    openfeign:
      lazy-attributes-resolution: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: ${oauth2_client_name}
            client-id: ${oauth2_client_id}
            client-secret: ${oauth2_client_secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: ${token_uri}
            user-info-uri: ${user_info_uri}
            user-name-attribute: ${user_attribute_name}
